task:
  name: Build
  env:
    USE_CCACHE: 1
    CIRRUS_WORKING_DIR: /tmp/$CIRRUS_REPO_NAME
    GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
    container:
      image: apon77/aosp:latest # It has built-in setup environment + repo, aria2, rclone, pigz, username ci, and email ci@ci.ci [You can use your own docker image if you want, or you can use this one too!]
      cpu: 8  #8 or less cpu for dummy build, 8 cpu for the final build, 8cpu highest for free accounts. Don't try to use more than 8cpu as free user, you may get blocked by ci.
      memory: 16G # So that we can have ram when needed, 32G highest
  sync_script:
    - git config --global user.email jashvakharia@gmail.com
    - git config --global user.name jash
    - git config --global credential.helper cache
    - repo init -u https://github.com/Ancient-Roms/manifest -b eleven
    - repo sync -j32
  build_script:
    - ./build.sh
